"""Add Review Model

Revision ID: fb7a2192ab1a
Revises: 932f44608bcf
Create Date: 2023-09-05 05:00:35.557576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb7a2192ab1a'
down_revision = '932f44608bcf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
